name: CI/CD Pipeline dengan Docker

on:
  push:
    branches: [ main ]

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Izin untuk menulis package

    steps:
      # Langkah 1: Mengunduh kode dari repo ke server virtual
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Langkah 2: Login ke registry container milik GitHub
      - name: Login ke GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Langkah 3: Build dan Push image Docker
      # Baris 'tags' di bawah ini sudah disesuaikan untuk Anda
      - name: Build dan Push Docker Image ke ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/rusdifn08/belajar-cicd-web:latest
